runtime: php83

handlers:
# Serve a directory as a static resource.
- url: /public/assets
  static_dir: assets


# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$

# Serve your app through a front controller at index.php or public/index.php.
- url: .*
  script: auto

env_variables:
  GOOGLE_STORAGE_BUCKET: picture-storage
  # populate these to use the "mysql" or "postres" backends
  CLOUDSQL_CONNECTION_NAME: sample-application:us-central1:bookshelf
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: passw0rd!
  CLOUDSQL_DATABASE_NAME: book-data
  APACHE_RUN_USER: www-data
  APACHE_RUN_GROUP: www-data
  APACHE_RUN_DIR: /var/run/apache2$SUFFIX
  APACHE_LOCK_DIR: /var/lock/apache2$SUFFIX
  APACHE_LOG_DIR: /var/log/apache2$SUFFIX
  MYSQL_ROOT_PASSWORD: admin
  MYSQL_DATABASE: patinhas
  MYSQL_USER: wellington
  MYSQL_PASSWORD: Univesp2022
  PMA_HOST: database