version: '3.8'

services:
  webserver:
    build: .
    container_name: patinhas_app
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: arm64v8/mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: patinhas_db
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: patinhas_phpmyadmin
    env_file: .env
    ports:
      - "8081:80"
    depends_on:
      - database
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge